### ISSUE TITLE
No way to contact or create an account if we are not in the list of accepted email provider

### ISSUE THREAD

**Issue by Xwilarg** [Tenpi/Moebooru.moe#4]
Hey,

So I wanted to have a look at this project but I was neither able to create an account of contact you using the contact form because I'm getting the following error:
```
Email provider not accepted. Allowed providers : gmail.com, icloud.com, yahoo.com, hotmail.com, outlook.com.
```

I'm using Proton Mail as a mail provider

**Comment by Tenpi** [comment]
Hi, as a spam preventative measure I block people from making accounts with disposable emails.

But I have added some other reputable mail providers to the whitelist such as ProtonMail, AOL, and Zoho.
